/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const posts = sqliteTable(
  "posts",
  {
    id: integer("id").primaryKey(),
    slug: text("slug"),
    status: text("status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    _status: text("_status", { enum: ["draft", "published"] }).default("draft"),
  },
  (columns) => [
    uniqueIndex("posts_slug_idx").on(columns.slug),
    index("posts_author_idx").on(columns.author),
    index("posts_updated_at_idx").on(columns.updatedAt),
    index("posts_created_at_idx").on(columns.createdAt),
    index("posts__status_idx").on(columns._status),
  ],
);

export const posts_locales = sqliteTable(
  "posts_locales",
  {
    title: text("title"),
    content: text("content", { mode: "json" }),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("posts_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [posts.id],
      name: "posts_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _posts_v = sqliteTable(
  "_posts_v",
  {
    id: integer("id").primaryKey(),
    parent: integer("parent_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    version_slug: text("version_slug"),
    version_status: text("version_status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    version_publishedAt: text("version_published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_author: integer("version_author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    version_updatedAt: text("version_updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_createdAt: text("version_created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version__status: text("version__status", {
      enum: ["draft", "published"],
    }).default("draft"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    snapshot: integer("snapshot", { mode: "boolean" }),
    publishedLocale: text("published_locale", { enum: ["vi", "en"] }),
    latest: integer("latest", { mode: "boolean" }),
  },
  (columns) => [
    index("_posts_v_parent_idx").on(columns.parent),
    index("_posts_v_version_version_slug_idx").on(columns.version_slug),
    index("_posts_v_version_version_author_idx").on(columns.version_author),
    index("_posts_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_posts_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_posts_v_version_version__status_idx").on(columns.version__status),
    index("_posts_v_created_at_idx").on(columns.createdAt),
    index("_posts_v_updated_at_idx").on(columns.updatedAt),
    index("_posts_v_snapshot_idx").on(columns.snapshot),
    index("_posts_v_published_locale_idx").on(columns.publishedLocale),
    index("_posts_v_latest_idx").on(columns.latest),
  ],
);

export const _posts_v_locales = sqliteTable(
  "_posts_v_locales",
  {
    version_title: text("version_title"),
    version_content: text("version_content", { mode: "json" }),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_posts_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_posts_v.id],
      name: "_posts_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    postsID: integer("posts_id"),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_posts_id_idx").on(columns.postsID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["postsID"]],
      foreignColumns: [posts.id],
      name: "payload_locked_documents_rels_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: "_locales",
  }),
}));
export const relations_posts = relations(posts, ({ one, many }) => ({
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: "author",
  }),
  _locales: many(posts_locales, {
    relationName: "_locales",
  }),
}));
export const relations__posts_v_locales = relations(
  _posts_v_locales,
  ({ one }) => ({
    _parentID: one(_posts_v, {
      fields: [_posts_v_locales._parentID],
      references: [_posts_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: "parent",
  }),
  version_author: one(users, {
    fields: [_posts_v.version_author],
    references: [users.id],
    relationName: "version_author",
  }),
  _locales: many(_posts_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: "posts",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  posts: typeof posts;
  posts_locales: typeof posts_locales;
  _posts_v: typeof _posts_v;
  _posts_v_locales: typeof _posts_v_locales;
  payload_kv: typeof payload_kv;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_posts_locales: typeof relations_posts_locales;
  relations_posts: typeof relations_posts;
  relations__posts_v_locales: typeof relations__posts_v_locales;
  relations__posts_v: typeof relations__posts_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
