/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    roles: Role;
    admins: Admin;
    users: User;
    posts: Post;
    pages: Page;
    showcases: Showcase;
    categories: Category;
    products: Product;
    carts: Cart;
    'cart-items': CartItem;
    orders: Order;
    'order-items': OrderItem;
    wishlists: Wishlist;
    'contact-inquiries': ContactInquiry;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    roles: RolesSelect<false> | RolesSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    showcases: ShowcasesSelect<false> | ShowcasesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    'company-info': CompanyInfo;
  };
  globalsSelect: {
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
  };
  locale: 'vi' | 'en';
  user: Admin & {
    collection: 'admins';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Display name of the role
   */
  name: string;
  /**
   * Unique identifier for the role (lowercase, no spaces)
   */
  slug: string;
  /**
   * Brief description of this role's purpose
   */
  description?: string | null;
  /**
   * System roles cannot be deleted
   */
  isSystem?: boolean | null;
  /**
   * Order in role selection dropdown
   */
  displayOrder?: number | null;
  /**
   * Define what this role can do in each collection
   */
  permissions?:
    | {
        collection:
          | 'posts'
          | 'products'
          | 'categories'
          | 'media'
          | 'users'
          | 'pages'
          | 'showcases'
          | 'carts'
          | 'orders';
        view?: boolean | null;
        create?: boolean | null;
        update?: boolean | null;
        delete?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  /**
   * User role determines permissions automatically
   */
  role: number | Role;
  /**
   * Contact phone number
   */
  phone?: string | null;
  /**
   * Account status
   */
  status: 'active' | 'inactive';
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  email: string;
  /**
   * Contact phone number
   */
  phone?: string | null;
  /**
   * Full address
   */
  address?: string | null;
  /**
   * Account status
   */
  status: 'active' | 'inactive' | 'suspended';
  verified?: boolean | null;
  lastLogin?: string | null;
  /**
   * Receive product updates and news
   */
  newsletter?: boolean | null;
  preferences?: {
    language?: ('vi' | 'en') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title if left empty. Type title first to see auto-generated slug.
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for preview
   */
  excerpt?: string | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * Defaults to current user
   */
  author: number | Admin;
  /**
   * Show on home page as featured post
   */
  featured?: boolean | null;
  /**
   * Sort order for featured posts on home page (lower numbers appear first)
   */
  displayOrder: number;
  /**
   * Custom title for search engines (overrides post title)
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO
   */
  alt?: string | null;
  /**
   * Optional caption displayed with the image
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    featured?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title if left empty. Type title first to see auto-generated slug.
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for preview
   */
  excerpt?: string | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * Show on home page as featured page
   */
  featured?: boolean | null;
  /**
   * Sort order for featured pages on home page (lower numbers appear first)
   */
  displayOrder: number;
  /**
   * Custom title for search engines (overrides page title)
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  featuredImage?: (number | null) | Media;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcases".
 */
export interface Showcase {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title if left empty. Type title first to see auto-generated slug.
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for preview
   */
  excerpt?: string | null;
  category: 'project' | 'case-study' | 'achievement' | 'partnership' | 'award' | 'other';
  /**
   * Showcase images (multiple images supported)
   */
  images?: (number | Media)[] | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Show on home page as featured showcase
   */
  featured?: boolean | null;
  /**
   * Sort order for display (lower numbers appear first)
   */
  displayOrder: number;
  /**
   * Client or partner name (if applicable)
   */
  client?: string | null;
  /**
   * Project/achievement date
   */
  date?: string | null;
  /**
   * Project/event location (if applicable)
   */
  location?: string | null;
  /**
   * Custom title for search engines (overrides showcase title)
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from name if left empty. Type name first to see auto-generated slug.
   */
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  /**
   * Lower numbers appear first
   */
  displayOrder: number;
  status: 'active' | 'inactive';
  /**
   * Custom title for search engines
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from name if left empty. Type name first to see auto-generated slug.
   */
  slug: string;
  /**
   * Product photos (multiple images supported)
   */
  images?: (number | Media)[] | null;
  /**
   * 1️⃣ First, add options like Color, Size, Material. Then click "Generate Variants" button below.
   */
  options?:
    | {
        /**
         * Option name (e.g., Color)
         */
        name: string;
        /**
         * Add option values here
         */
        values: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * 2️⃣ Variants are auto-generated from options above. Update price, SKU, and inventory for each variant.
   */
  variants?:
    | {
        /**
         * ✅ Auto-generated from selected options (e.g., "Red / Small")
         */
        title: string;
        /**
         * Selected option values for this variant
         */
        selectedOptions: {
          /**
           * Option name (e.g., Color)
           */
          option: string;
          /**
           * Option value (e.g., Red)
           */
          value: string;
          id?: string | null;
        }[];
        /**
         * Selling price
         */
        price: number;
        /**
         * Original price (for discounts)
         */
        compareAtPrice?: number | null;
        /**
         * Stock Keeping Unit
         */
        sku?: string | null;
        /**
         * Barcode (ISBN, UPC, GTIN, etc.)
         */
        barcode?: string | null;
        /**
         * Available quantity
         */
        inventory: number;
        /**
         * Specific image for this variant (optional)
         */
        image?: (number | null) | Media;
        /**
         * Make this variant available for purchase
         */
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full product description with formatting
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short summary for listings and previews
   */
  excerpt?: string | null;
  /**
   * Technical specifications and details
   */
  specifications?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Product benefits and advantages
   */
  benefits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How to use the product
   */
  usageInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select one or more categories for this product
   */
  categories: (number | Category)[];
  /**
   * Show on home page as featured product
   */
  featured?: boolean | null;
  /**
   * Highlight as best-selling product
   */
  bestSeller?: boolean | null;
  /**
   * Sort order for featured products on home page (lower numbers appear first)
   */
  displayOrder: number;
  status: 'draft' | 'published' | 'archived';
  /**
   * Custom title for search engines (overrides product name)
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  /**
   * User who owns this cart (null for guest carts)
   */
  user?: (number | null) | User;
  /**
   * Session ID for guest carts
   */
  sessionId?: string | null;
  /**
   * Total number of items in cart
   */
  itemsCount?: number | null;
  /**
   * Subtotal before discounts and shipping (VND)
   */
  subtotal?: number | null;
  /**
   * Total discount amount (VND)
   */
  discount?: number | null;
  /**
   * Total amount (VND)
   */
  total?: number | null;
  /**
   * Applied coupon code
   */
  couponCode?: string | null;
  status: 'active' | 'abandoned' | 'converted' | 'expired';
  createdAt: string;
  updatedAt: string;
  /**
   * Cart expiration date (typically 30 days)
   */
  expiresAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: number;
  cart: number | Cart;
  product: number | Product;
  quantity: number;
  /**
   * Price at time of adding to cart (VND)
   */
  price: number;
  addedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order identifier (e.g., ORD-2024-00001)
   */
  orderNumber: string;
  /**
   * Customer who placed the order (null for guest orders)
   */
  user?: (number | null) | User;
  /**
   * Customer information for guest orders
   */
  guestCustomer?: {
    email?: string | null;
    name?: string | null;
    phone?: string | null;
  };
  shippingAddress: {
    fullName: string;
    phone: string;
    address: string;
    ward?: string | null;
    district: string;
    city: string;
    postalCode?: string | null;
  };
  billingAddress?: {
    sameAsShipping?: boolean | null;
    fullName?: string | null;
    phone?: string | null;
    address?: string | null;
    ward?: string | null;
    district?: string | null;
    city?: string | null;
    postalCode?: string | null;
  };
  itemsCount?: number | null;
  /**
   * Sum of all items before discounts and shipping (VND)
   */
  subtotal: number;
  /**
   * Total discount amount (VND)
   */
  discount?: number | null;
  /**
   * Shipping cost (VND)
   */
  shippingFee?: number | null;
  /**
   * Tax amount (VND)
   */
  tax?: number | null;
  /**
   * Final total amount (VND)
   */
  total: number;
  couponCode?: string | null;
  paymentMethod: 'cod' | 'bank-transfer' | 'credit-card' | 'e-wallet';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Payment gateway transaction ID
   */
  transactionId?: string | null;
  shippingMethod: 'standard' | 'express' | 'same-day';
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  status: 'pending' | 'confirmed' | 'processing' | 'shipping' | 'delivered' | 'completed' | 'cancelled' | 'refunded';
  /**
   * Notes from customer
   */
  customerNotes?: string | null;
  /**
   * Internal notes (not visible to customer)
   */
  adminNotes?: string | null;
  createdAt: string;
  updatedAt: string;
  confirmedAt?: string | null;
  shippedAt?: string | null;
  deliveredAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  /**
   * Product details at time of order
   */
  productSnapshot?: {
    name?: string | null;
    sku?: string | null;
    image?: string | null;
  };
  quantity: number;
  /**
   * Price per unit at time of order (VND)
   */
  price: number;
  /**
   * Quantity × Unit Price (VND)
   */
  subtotal: number;
  /**
   * Discount applied to this item (VND)
   */
  discount?: number | null;
  /**
   * Subtotal - Discount (VND)
   */
  total: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  /**
   * User who saved this product
   */
  user: number | User;
  /**
   * Product saved to wishlist
   */
  product: number | Product;
  /**
   * Personal notes about this product
   */
  notes?: string | null;
  /**
   * How much the user wants this product
   */
  priority?: ('low' | 'medium' | 'high') | null;
  /**
   * Send notification when product price drops
   */
  notifyOnPriceChange?: boolean | null;
  /**
   * Send notification when out-of-stock product is available again
   */
  notifyOnBackInStock?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  phone: string;
  message: string;
  /**
   * Follow-up status (editable by admin)
   */
  status: 'new' | 'in-progress' | 'responded' | 'closed';
  /**
   * Internal notes about this inquiry (not visible to visitor)
   */
  notes?: string | null;
  submittedAt: string;
  /**
   * Visitor IP for spam prevention
   */
  ipAddress?: string | null;
  /**
   * Browser information for analytics
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'showcases';
        value: number | Showcase;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: number | CartItem;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isSystem?: T;
  displayOrder?: T;
  permissions?:
    | T
    | {
        collection?: T;
        view?: T;
        create?: T;
        update?: T;
        delete?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  status?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  status?: T;
  verified?: T;
  lastLogin?: T;
  newsletter?: T;
  preferences?:
    | T
    | {
        language?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  featured?: T;
  displayOrder?: T;
  seoTitle?: T;
  seoDescription?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  publishedAt?: T;
  featured?: T;
  displayOrder?: T;
  seoTitle?: T;
  seoDescription?: T;
  featuredImage?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcases_select".
 */
export interface ShowcasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  excerpt?: T;
  category?: T;
  images?: T;
  status?: T;
  featured?: T;
  displayOrder?: T;
  client?: T;
  date?: T;
  location?: T;
  seoTitle?: T;
  seoDescription?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  images?: T;
  options?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        title?: T;
        selectedOptions?:
          | T
          | {
              option?: T;
              value?: T;
              id?: T;
            };
        price?: T;
        compareAtPrice?: T;
        sku?: T;
        barcode?: T;
        inventory?: T;
        image?: T;
        available?: T;
        id?: T;
      };
  description?: T;
  excerpt?: T;
  specifications?: T;
  benefits?: T;
  usageInstructions?: T;
  categories?: T;
  featured?: T;
  bestSeller?: T;
  displayOrder?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  sessionId?: T;
  itemsCount?: T;
  subtotal?: T;
  discount?: T;
  total?: T;
  couponCode?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
  expiresAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  cart?: T;
  product?: T;
  quantity?: T;
  price?: T;
  addedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  guestCustomer?:
    | T
    | {
        email?: T;
        name?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        address?: T;
        ward?: T;
        district?: T;
        city?: T;
        postalCode?: T;
      };
  billingAddress?:
    | T
    | {
        sameAsShipping?: T;
        fullName?: T;
        phone?: T;
        address?: T;
        ward?: T;
        district?: T;
        city?: T;
        postalCode?: T;
      };
  itemsCount?: T;
  subtotal?: T;
  discount?: T;
  shippingFee?: T;
  tax?: T;
  total?: T;
  couponCode?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  transactionId?: T;
  shippingMethod?: T;
  trackingNumber?: T;
  status?: T;
  customerNotes?: T;
  adminNotes?: T;
  createdAt?: T;
  updatedAt?: T;
  confirmedAt?: T;
  shippedAt?: T;
  deliveredAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  productSnapshot?:
    | T
    | {
        name?: T;
        sku?: T;
        image?: T;
      };
  quantity?: T;
  price?: T;
  subtotal?: T;
  discount?: T;
  total?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  notes?: T;
  priority?: T;
  notifyOnPriceChange?: T;
  notifyOnBackInStock?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  notes?: T;
  submittedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        featured?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  /**
   * Official company name
   */
  companyName: string;
  /**
   * Company tagline or slogan
   */
  tagline?: string | null;
  /**
   * Company logo image (SVG or PNG recommended)
   */
  logo: number | Media;
  /**
   * Brief company overview for home page
   */
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Company vision statement
   */
  vision: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Company mission statement
   */
  mission: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Company core values
   */
  coreValues: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Physical company address
   */
  address: string;
  /**
   * Contact phone number
   */
  phone: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Social media links (optional)
   */
  socialMedia?:
    | {
        platform: 'facebook' | 'linkedin' | 'youtube' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  overview?: T;
  vision?: T;
  mission?: T;
  coreValues?: T;
  address?: T;
  phone?: T;
  email?: T;
  socialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}