/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const roles_permissions = sqliteTable(
  "roles_permissions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    collection: text("collection", {
      enum: [
        "posts",
        "products",
        "categories",
        "media",
        "users",
        "pages",
        "showcases",
        "carts",
        "orders",
      ],
    }).notNull(),
    view: integer("view", { mode: "boolean" }).default(false),
    create: integer("create", { mode: "boolean" }).default(false),
    update: integer("update", { mode: "boolean" }).default(false),
    delete: integer("delete", { mode: "boolean" }).default(false),
  },
  (columns) => [
    index("roles_permissions_order_idx").on(columns._order),
    index("roles_permissions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [roles.id],
      name: "roles_permissions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const roles = sqliteTable(
  "roles",
  {
    id: integer("id").primaryKey(),
    slug: text("slug").notNull(),
    isSystem: integer("is_system", { mode: "boolean" }).default(false),
    displayOrder: numeric("display_order", { mode: "number" }).default(0),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("roles_slug_idx").on(columns.slug),
    index("roles_updated_at_idx").on(columns.updatedAt),
    index("roles_created_at_idx").on(columns.createdAt),
  ],
);

export const roles_locales = sqliteTable(
  "roles_locales",
  {
    name: text("name").notNull(),
    description: text("description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("roles_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [roles.id],
      name: "roles_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const admins_sessions = sqliteTable(
  "admins_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("admins_sessions_order_idx").on(columns._order),
    index("admins_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [admins.id],
      name: "admins_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const admins = sqliteTable(
  "admins",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    role: integer("role_id")
      .notNull()
      .references(() => roles.id, {
        onDelete: "set null",
      }),
    phone: text("phone"),
    status: text("status", { enum: ["active", "inactive"] })
      .notNull()
      .default("active"),
    lastLogin: text("last_login").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("admins_role_idx").on(columns.role),
    index("admins_updated_at_idx").on(columns.updatedAt),
    index("admins_created_at_idx").on(columns.createdAt),
    uniqueIndex("admins_email_idx").on(columns.email),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    phone: text("phone"),
    address: text("address"),
    status: text("status", { enum: ["active", "inactive", "suspended"] })
      .notNull()
      .default("active"),
    verified: integer("verified", { mode: "boolean" }).default(false),
    lastLogin: text("last_login").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    newsletter: integer("newsletter", { mode: "boolean" }).default(false),
    preferences_language: text("preferences_language", {
      enum: ["vi", "en"],
    }).default("vi"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
  ],
);

export const posts = sqliteTable(
  "posts",
  {
    id: integer("id").primaryKey(),
    slug: text("slug"),
    excerpt: text("excerpt"),
    status: text("status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    author: integer("author_id").references(() => admins.id, {
      onDelete: "set null",
    }),
    featured: integer("featured", { mode: "boolean" }).default(false),
    displayOrder: numeric("display_order", { mode: "number" }).default(0),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    _status: text("_status", { enum: ["draft", "published"] }).default("draft"),
  },
  (columns) => [
    uniqueIndex("posts_slug_idx").on(columns.slug),
    index("posts_author_idx").on(columns.author),
    index("posts_featured_image_idx").on(columns.featuredImage),
    index("posts_updated_at_idx").on(columns.updatedAt),
    index("posts_created_at_idx").on(columns.createdAt),
    index("posts__status_idx").on(columns._status),
  ],
);

export const posts_locales = sqliteTable(
  "posts_locales",
  {
    title: text("title"),
    content: text("content", { mode: "json" }),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("posts_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [posts.id],
      name: "posts_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _posts_v = sqliteTable(
  "_posts_v",
  {
    id: integer("id").primaryKey(),
    parent: integer("parent_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    version_slug: text("version_slug"),
    version_excerpt: text("version_excerpt"),
    version_status: text("version_status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    version_publishedAt: text("version_published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_author: integer("version_author_id").references(() => admins.id, {
      onDelete: "set null",
    }),
    version_featured: integer("version_featured", { mode: "boolean" }).default(
      false,
    ),
    version_displayOrder: numeric("version_display_order", {
      mode: "number",
    }).default(0),
    version_featuredImage: integer("version_featured_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: text("version_updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_createdAt: text("version_created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version__status: text("version__status", {
      enum: ["draft", "published"],
    }).default("draft"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    snapshot: integer("snapshot", { mode: "boolean" }),
    publishedLocale: text("published_locale", { enum: ["vi", "en"] }),
    latest: integer("latest", { mode: "boolean" }),
  },
  (columns) => [
    index("_posts_v_parent_idx").on(columns.parent),
    index("_posts_v_version_version_slug_idx").on(columns.version_slug),
    index("_posts_v_version_version_author_idx").on(columns.version_author),
    index("_posts_v_version_version_featured_image_idx").on(
      columns.version_featuredImage,
    ),
    index("_posts_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_posts_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_posts_v_version_version__status_idx").on(columns.version__status),
    index("_posts_v_created_at_idx").on(columns.createdAt),
    index("_posts_v_updated_at_idx").on(columns.updatedAt),
    index("_posts_v_snapshot_idx").on(columns.snapshot),
    index("_posts_v_published_locale_idx").on(columns.publishedLocale),
    index("_posts_v_latest_idx").on(columns.latest),
  ],
);

export const _posts_v_locales = sqliteTable(
  "_posts_v_locales",
  {
    version_title: text("version_title"),
    version_content: text("version_content", { mode: "json" }),
    version_seoTitle: text("version_seo_title"),
    version_seoDescription: text("version_seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_posts_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_posts_v.id],
      name: "_posts_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = sqliteTable(
  "pages",
  {
    id: integer("id").primaryKey(),
    slug: text("slug").notNull(),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    featured: integer("featured", { mode: "boolean" }).default(false),
    displayOrder: numeric("display_order", { mode: "number" })
      .notNull()
      .default(0),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_featured_image_idx").on(columns.featuredImage),
  ],
);

export const pages_locales = sqliteTable(
  "pages_locales",
  {
    title: text("title").notNull(),
    content: text("content", { mode: "json" }).notNull(),
    excerpt: text("excerpt"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const showcases = sqliteTable(
  "showcases",
  {
    id: integer("id").primaryKey(),
    slug: text("slug").notNull(),
    category: text("category", {
      enum: [
        "project",
        "case-study",
        "achievement",
        "partnership",
        "award",
        "other",
      ],
    }).notNull(),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    featured: integer("featured", { mode: "boolean" }).default(false),
    displayOrder: numeric("display_order", { mode: "number" })
      .notNull()
      .default(0),
    date: text("date").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [uniqueIndex("showcases_slug_idx").on(columns.slug)],
);

export const showcases_locales = sqliteTable(
  "showcases_locales",
  {
    title: text("title").notNull(),
    description: text("description", { mode: "json" }).notNull(),
    excerpt: text("excerpt"),
    client: text("client"),
    location: text("location"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("showcases_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [showcases.id],
      name: "showcases_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const showcases_rels = sqliteTable(
  "showcases_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("showcases_rels_order_idx").on(columns.order),
    index("showcases_rels_parent_idx").on(columns.parent),
    index("showcases_rels_path_idx").on(columns.path),
    index("showcases_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [showcases.id],
      name: "showcases_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "showcases_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const categories = sqliteTable(
  "categories",
  {
    id: integer("id").primaryKey(),
    slug: text("slug").notNull(),
    displayOrder: numeric("display_order", { mode: "number" })
      .notNull()
      .default(0),
    status: text("status", { enum: ["active", "inactive"] })
      .notNull()
      .default("active"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const categories_locales = sqliteTable(
  "categories_locales",
  {
    name: text("name").notNull(),
    description: text("description"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("categories_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [categories.id],
      name: "categories_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_options_values = sqliteTable(
  "products_options_values",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
  },
  (columns) => [
    index("products_options_values_order_idx").on(columns._order),
    index("products_options_values_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products_options.id],
      name: "products_options_values_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_options_values_locales = sqliteTable(
  "products_options_values_locales",
  {
    label: text("label"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: text("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("products_options_values_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products_options_values.id],
      name: "products_options_values_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_options = sqliteTable(
  "products_options",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
  },
  (columns) => [
    index("products_options_order_idx").on(columns._order),
    index("products_options_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_options_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_options_locales = sqliteTable(
  "products_options_locales",
  {
    name: text("name"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: text("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("products_options_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products_options.id],
      name: "products_options_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_variants_selected_options = sqliteTable(
  "products_variants_selected_options",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    optionId: text("option_id"),
    optionValueId: text("option_value_id"),
  },
  (columns) => [
    index("products_variants_selected_options_order_idx").on(columns._order),
    index("products_variants_selected_options_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products_variants.id],
      name: "products_variants_selected_options_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_variants = sqliteTable(
  "products_variants",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    price: numeric("price", { mode: "number" }).default(0),
    compareAtPrice: numeric("compare_at_price", { mode: "number" }),
    sku: text("sku"),
    barcode: text("barcode"),
    inventory: numeric("inventory", { mode: "number" }).default(0),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    available: integer("available", { mode: "boolean" }).default(true),
  },
  (columns) => [
    index("products_variants_order_idx").on(columns._order),
    index("products_variants_parent_id_idx").on(columns._parentID),
    index("products_variants_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_variants_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_variants_locales = sqliteTable(
  "products_variants_locales",
  {
    title: text("title"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: text("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("products_variants_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products_variants.id],
      name: "products_variants_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products = sqliteTable(
  "products",
  {
    id: integer("id").primaryKey(),
    slug: text("slug"),
    featured: integer("featured", { mode: "boolean" }).default(false),
    bestSeller: integer("best_seller", { mode: "boolean" }).default(false),
    displayOrder: numeric("display_order", { mode: "number" }).default(0),
    status: text("status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    _status: text("_status", { enum: ["draft", "published"] }).default("draft"),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
    index("products__status_idx").on(columns._status),
  ],
);

export const products_locales = sqliteTable(
  "products_locales",
  {
    name: text("name"),
    description: text("description", { mode: "json" }),
    excerpt: text("excerpt"),
    specifications: text("specifications", { mode: "json" }),
    benefits: text("benefits", { mode: "json" }),
    usageInstructions: text("usage_instructions", { mode: "json" }),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("products_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_rels = sqliteTable(
  "products_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    mediaID: integer("media_id"),
    categoriesID: integer("categories_id"),
  },
  (columns) => [
    index("products_rels_order_idx").on(columns.order),
    index("products_rels_parent_idx").on(columns.parent),
    index("products_rels_path_idx").on(columns.path),
    index("products_rels_media_id_idx").on(columns.mediaID),
    index("products_rels_categories_id_idx").on(columns.categoriesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [products.id],
      name: "products_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "products_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "products_rels_categories_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_options_values = sqliteTable(
  "_products_v_version_options_values",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: integer("id").primaryKey(),
    _uuid: text("_uuid"),
  },
  (columns) => [
    index("_products_v_version_options_values_order_idx").on(columns._order),
    index("_products_v_version_options_values_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v_version_options.id],
      name: "_products_v_version_options_values_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_options_values_locales = sqliteTable(
  "_products_v_version_options_values_locales",
  {
    label: text("label"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "_products_v_version_options_values_locales_locale_parent_id_",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v_version_options_values.id],
      name: "_products_v_version_options_values_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_options = sqliteTable(
  "_products_v_version_options",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: integer("id").primaryKey(),
    _uuid: text("_uuid"),
  },
  (columns) => [
    index("_products_v_version_options_order_idx").on(columns._order),
    index("_products_v_version_options_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v.id],
      name: "_products_v_version_options_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_options_locales = sqliteTable(
  "_products_v_version_options_locales",
  {
    name: text("name"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "_products_v_version_options_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v_version_options.id],
      name: "_products_v_version_options_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_variants_selected_options = sqliteTable(
  "_products_v_version_variants_selected_options",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: integer("id").primaryKey(),
    optionId: text("option_id"),
    optionValueId: text("option_value_id"),
    _uuid: text("_uuid"),
  },
  (columns) => [
    index("_products_v_version_variants_selected_options_order_idx").on(
      columns._order,
    ),
    index("_products_v_version_variants_selected_options_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v_version_variants.id],
      name: "_products_v_version_variants_selected_options_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_variants = sqliteTable(
  "_products_v_version_variants",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: integer("id").primaryKey(),
    price: numeric("price", { mode: "number" }).default(0),
    compareAtPrice: numeric("compare_at_price", { mode: "number" }),
    sku: text("sku"),
    barcode: text("barcode"),
    inventory: numeric("inventory", { mode: "number" }).default(0),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    available: integer("available", { mode: "boolean" }).default(true),
    _uuid: text("_uuid"),
  },
  (columns) => [
    index("_products_v_version_variants_order_idx").on(columns._order),
    index("_products_v_version_variants_parent_id_idx").on(columns._parentID),
    index("_products_v_version_variants_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v.id],
      name: "_products_v_version_variants_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_version_variants_locales = sqliteTable(
  "_products_v_version_variants_locales",
  {
    title: text("title"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "_products_v_version_variants_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v_version_variants.id],
      name: "_products_v_version_variants_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v = sqliteTable(
  "_products_v",
  {
    id: integer("id").primaryKey(),
    parent: integer("parent_id").references(() => products.id, {
      onDelete: "set null",
    }),
    version_slug: text("version_slug"),
    version_featured: integer("version_featured", { mode: "boolean" }).default(
      false,
    ),
    version_bestSeller: integer("version_best_seller", {
      mode: "boolean",
    }).default(false),
    version_displayOrder: numeric("version_display_order", {
      mode: "number",
    }).default(0),
    version_status: text("version_status", {
      enum: ["draft", "published", "archived"],
    }).default("draft"),
    version_updatedAt: text("version_updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_createdAt: text("version_created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version__status: text("version__status", {
      enum: ["draft", "published"],
    }).default("draft"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    snapshot: integer("snapshot", { mode: "boolean" }),
    publishedLocale: text("published_locale", { enum: ["vi", "en"] }),
    latest: integer("latest", { mode: "boolean" }),
  },
  (columns) => [
    index("_products_v_parent_idx").on(columns.parent),
    index("_products_v_version_version_slug_idx").on(columns.version_slug),
    index("_products_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_products_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_products_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_products_v_created_at_idx").on(columns.createdAt),
    index("_products_v_updated_at_idx").on(columns.updatedAt),
    index("_products_v_snapshot_idx").on(columns.snapshot),
    index("_products_v_published_locale_idx").on(columns.publishedLocale),
    index("_products_v_latest_idx").on(columns.latest),
  ],
);

export const _products_v_locales = sqliteTable(
  "_products_v_locales",
  {
    version_name: text("version_name"),
    version_description: text("version_description", { mode: "json" }),
    version_excerpt: text("version_excerpt"),
    version_specifications: text("version_specifications", { mode: "json" }),
    version_benefits: text("version_benefits", { mode: "json" }),
    version_usageInstructions: text("version_usage_instructions", {
      mode: "json",
    }),
    version_seoTitle: text("version_seo_title"),
    version_seoDescription: text("version_seo_description"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_products_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v.id],
      name: "_products_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v_rels = sqliteTable(
  "_products_v_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    mediaID: integer("media_id"),
    categoriesID: integer("categories_id"),
  },
  (columns) => [
    index("_products_v_rels_order_idx").on(columns.order),
    index("_products_v_rels_parent_idx").on(columns.parent),
    index("_products_v_rels_path_idx").on(columns.path),
    index("_products_v_rels_media_id_idx").on(columns.mediaID),
    index("_products_v_rels_categories_id_idx").on(columns.categoriesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_products_v.id],
      name: "_products_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "_products_v_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "_products_v_rels_categories_fk",
    }).onDelete("cascade"),
  ],
);

export const carts = sqliteTable(
  "carts",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    sessionId: text("session_id"),
    itemsCount: numeric("items_count", { mode: "number" }).default(0),
    subtotal: numeric("subtotal", { mode: "number" }).default(0),
    discount: numeric("discount", { mode: "number" }).default(0),
    total: numeric("total", { mode: "number" }).default(0),
    couponCode: text("coupon_code"),
    status: text("status", {
      enum: ["active", "abandoned", "converted", "expired"],
    })
      .notNull()
      .default("active"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text("expires_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("carts_user_idx").on(columns.user),
    index("carts_session_id_idx").on(columns.sessionId),
  ],
);

export const cart_items = sqliteTable(
  "cart_items",
  {
    id: integer("id").primaryKey(),
    cart: integer("cart_id")
      .notNull()
      .references(() => carts.id, {
        onDelete: "set null",
      }),
    product: integer("product_id")
      .notNull()
      .references(() => products.id, {
        onDelete: "set null",
      }),
    quantity: numeric("quantity", { mode: "number" }).notNull().default(1),
    price: numeric("price", { mode: "number" }).notNull(),
    addedAt: text("added_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("cart_items_cart_idx").on(columns.cart),
    index("cart_items_product_idx").on(columns.product),
    index("cart_items_updated_at_idx").on(columns.updatedAt),
    index("cart_items_created_at_idx").on(columns.createdAt),
  ],
);

export const orders = sqliteTable(
  "orders",
  {
    id: integer("id").primaryKey(),
    orderNumber: text("order_number").notNull(),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    guestCustomer_email: text("guest_customer_email"),
    guestCustomer_name: text("guest_customer_name"),
    guestCustomer_phone: text("guest_customer_phone"),
    shippingAddress_fullName: text("shipping_address_full_name").notNull(),
    shippingAddress_phone: text("shipping_address_phone").notNull(),
    shippingAddress_address: text("shipping_address_address").notNull(),
    shippingAddress_ward: text("shipping_address_ward"),
    shippingAddress_district: text("shipping_address_district").notNull(),
    shippingAddress_city: text("shipping_address_city").notNull(),
    shippingAddress_postalCode: text("shipping_address_postal_code"),
    billingAddress_sameAsShipping: integer("billing_address_same_as_shipping", {
      mode: "boolean",
    }).default(true),
    billingAddress_fullName: text("billing_address_full_name"),
    billingAddress_phone: text("billing_address_phone"),
    billingAddress_address: text("billing_address_address"),
    billingAddress_ward: text("billing_address_ward"),
    billingAddress_district: text("billing_address_district"),
    billingAddress_city: text("billing_address_city"),
    billingAddress_postalCode: text("billing_address_postal_code"),
    itemsCount: numeric("items_count", { mode: "number" }).default(0),
    subtotal: numeric("subtotal", { mode: "number" }).notNull(),
    discount: numeric("discount", { mode: "number" }).default(0),
    shippingFee: numeric("shipping_fee", { mode: "number" }).default(0),
    tax: numeric("tax", { mode: "number" }).default(0),
    total: numeric("total", { mode: "number" }).notNull(),
    couponCode: text("coupon_code"),
    paymentMethod: text("payment_method", {
      enum: ["cod", "bank-transfer", "credit-card", "e-wallet"],
    }).notNull(),
    paymentStatus: text("payment_status", {
      enum: ["pending", "paid", "failed", "refunded"],
    })
      .notNull()
      .default("pending"),
    transactionId: text("transaction_id"),
    shippingMethod: text("shipping_method", {
      enum: ["standard", "express", "same-day"],
    }).notNull(),
    trackingNumber: text("tracking_number"),
    status: text("status", {
      enum: [
        "pending",
        "confirmed",
        "processing",
        "shipping",
        "delivered",
        "completed",
        "cancelled",
        "refunded",
      ],
    })
      .notNull()
      .default("pending"),
    customerNotes: text("customer_notes"),
    adminNotes: text("admin_notes"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    confirmedAt: text("confirmed_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    shippedAt: text("shipped_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    deliveredAt: text("delivered_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    uniqueIndex("orders_order_number_idx").on(columns.orderNumber),
    index("orders_user_idx").on(columns.user),
  ],
);

export const order_items = sqliteTable(
  "order_items",
  {
    id: integer("id").primaryKey(),
    order: integer("order_id")
      .notNull()
      .references(() => orders.id, {
        onDelete: "set null",
      }),
    product: integer("product_id")
      .notNull()
      .references(() => products.id, {
        onDelete: "set null",
      }),
    productSnapshot_sku: text("product_snapshot_sku"),
    productSnapshot_image: text("product_snapshot_image"),
    quantity: numeric("quantity", { mode: "number" }).notNull(),
    price: numeric("price", { mode: "number" }).notNull(),
    subtotal: numeric("subtotal", { mode: "number" }).notNull(),
    discount: numeric("discount", { mode: "number" }).default(0),
    total: numeric("total", { mode: "number" }).notNull(),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("order_items_order_idx").on(columns.order),
    index("order_items_product_idx").on(columns.product),
    index("order_items_updated_at_idx").on(columns.updatedAt),
  ],
);

export const order_items_locales = sqliteTable(
  "order_items_locales",
  {
    productSnapshot_name: text("product_snapshot_name"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("order_items_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [order_items.id],
      name: "order_items_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const wishlists = sqliteTable(
  "wishlists",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    product: integer("product_id")
      .notNull()
      .references(() => products.id, {
        onDelete: "set null",
      }),
    notes: text("notes"),
    priority: text("priority", { enum: ["low", "medium", "high"] }).default(
      "medium",
    ),
    notifyOnPriceChange: integer("notify_on_price_change", {
      mode: "boolean",
    }).default(false),
    notifyOnBackInStock: integer("notify_on_back_in_stock", {
      mode: "boolean",
    }).default(false),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("wishlists_user_idx").on(columns.user),
    index("wishlists_product_idx").on(columns.product),
  ],
);

export const contact_inquiries = sqliteTable(
  "contact_inquiries",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    phone: text("phone").notNull(),
    message: text("message").notNull(),
    status: text("status", {
      enum: ["new", "in-progress", "responded", "closed"],
    })
      .notNull()
      .default("new"),
    notes: text("notes"),
    submittedAt: text("submitted_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("contact_inquiries_updated_at_idx").on(columns.updatedAt),
    index("contact_inquiries_created_at_idx").on(columns.createdAt),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: text("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: text("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: text("sizes_thumbnail_filename"),
    sizes_card_url: text("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: text("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: text("sizes_card_filename"),
    sizes_featured_url: text("sizes_featured_url"),
    sizes_featured_width: numeric("sizes_featured_width", { mode: "number" }),
    sizes_featured_height: numeric("sizes_featured_height", { mode: "number" }),
    sizes_featured_mimeType: text("sizes_featured_mime_type"),
    sizes_featured_filesize: numeric("sizes_featured_filesize", {
      mode: "number",
    }),
    sizes_featured_filename: text("sizes_featured_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_featured_sizes_featured_filename_idx").on(
      columns.sizes_featured_filename,
    ),
  ],
);

export const media_locales = sqliteTable(
  "media_locales",
  {
    alt: text("alt"),
    caption: text("caption"),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("media_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [media.id],
      name: "media_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    rolesID: integer("roles_id"),
    adminsID: integer("admins_id"),
    usersID: integer("users_id"),
    postsID: integer("posts_id"),
    pagesID: integer("pages_id"),
    showcasesID: integer("showcases_id"),
    categoriesID: integer("categories_id"),
    productsID: integer("products_id"),
    cartsID: integer("carts_id"),
    "cart-itemsID": integer("cart_items_id"),
    ordersID: integer("orders_id"),
    "order-itemsID": integer("order_items_id"),
    wishlistsID: integer("wishlists_id"),
    "contact-inquiriesID": integer("contact_inquiries_id"),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_roles_id_idx").on(columns.rolesID),
    index("payload_locked_documents_rels_admins_id_idx").on(columns.adminsID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_posts_id_idx").on(columns.postsID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_showcases_id_idx").on(
      columns.showcasesID,
    ),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    index("payload_locked_documents_rels_carts_id_idx").on(columns.cartsID),
    index("payload_locked_documents_rels_cart_items_id_idx").on(
      columns["cart-itemsID"],
    ),
    index("payload_locked_documents_rels_orders_id_idx").on(columns.ordersID),
    index("payload_locked_documents_rels_order_items_id_idx").on(
      columns["order-itemsID"],
    ),
    index("payload_locked_documents_rels_wishlists_id_idx").on(
      columns.wishlistsID,
    ),
    index("payload_locked_documents_rels_contact_inquiries_id_idx").on(
      columns["contact-inquiriesID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["rolesID"]],
      foreignColumns: [roles.id],
      name: "payload_locked_documents_rels_roles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_locked_documents_rels_admins_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["postsID"]],
      foreignColumns: [posts.id],
      name: "payload_locked_documents_rels_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["showcasesID"]],
      foreignColumns: [showcases.id],
      name: "payload_locked_documents_rels_showcases_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["cartsID"]],
      foreignColumns: [carts.id],
      name: "payload_locked_documents_rels_carts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["cart-itemsID"]],
      foreignColumns: [cart_items.id],
      name: "payload_locked_documents_rels_cart_items_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["ordersID"]],
      foreignColumns: [orders.id],
      name: "payload_locked_documents_rels_orders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["order-itemsID"]],
      foreignColumns: [order_items.id],
      name: "payload_locked_documents_rels_order_items_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["wishlistsID"]],
      foreignColumns: [wishlists.id],
      name: "payload_locked_documents_rels_wishlists_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["contact-inquiriesID"]],
      foreignColumns: [contact_inquiries.id],
      name: "payload_locked_documents_rels_contact_inquiries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    adminsID: integer("admins_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_admins_id_idx").on(columns.adminsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_preferences_rels_admins_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const company_info_social_media = sqliteTable(
  "company_info_social_media",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    platform: text("platform", {
      enum: ["facebook", "linkedin", "youtube", "twitter"],
    }).notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("company_info_social_media_order_idx").on(columns._order),
    index("company_info_social_media_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [company_info.id],
      name: "company_info_social_media_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const company_info = sqliteTable(
  "company_info",
  {
    id: integer("id").primaryKey(),
    logo: integer("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    phone: text("phone").notNull(),
    email: text("email").notNull(),
    updatedAt: text("updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [index("company_info_logo_idx").on(columns.logo)],
);

export const company_info_locales = sqliteTable(
  "company_info_locales",
  {
    companyName: text("company_name").notNull(),
    tagline: text("tagline"),
    overview: text("overview", { mode: "json" }).notNull(),
    vision: text("vision", { mode: "json" }).notNull(),
    mission: text("mission", { mode: "json" }).notNull(),
    coreValues: text("core_values", { mode: "json" }).notNull(),
    address: text("address").notNull(),
    id: integer("id").primaryKey(),
    _locale: text("_locale", { enum: ["vi", "en"] }).notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("company_info_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [company_info.id],
      name: "company_info_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_roles_permissions = relations(
  roles_permissions,
  ({ one }) => ({
    _parentID: one(roles, {
      fields: [roles_permissions._parentID],
      references: [roles.id],
      relationName: "permissions",
    }),
  }),
);
export const relations_roles_locales = relations(roles_locales, ({ one }) => ({
  _parentID: one(roles, {
    fields: [roles_locales._parentID],
    references: [roles.id],
    relationName: "_locales",
  }),
}));
export const relations_roles = relations(roles, ({ many }) => ({
  permissions: many(roles_permissions, {
    relationName: "permissions",
  }),
  _locales: many(roles_locales, {
    relationName: "_locales",
  }),
}));
export const relations_admins_sessions = relations(
  admins_sessions,
  ({ one }) => ({
    _parentID: one(admins, {
      fields: [admins_sessions._parentID],
      references: [admins.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_admins = relations(admins, ({ one, many }) => ({
  role: one(roles, {
    fields: [admins.role],
    references: [roles.id],
    relationName: "role",
  }),
  sessions: many(admins_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_users = relations(users, () => ({}));
export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: "_locales",
  }),
}));
export const relations_posts = relations(posts, ({ one, many }) => ({
  author: one(admins, {
    fields: [posts.author],
    references: [admins.id],
    relationName: "author",
  }),
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  _locales: many(posts_locales, {
    relationName: "_locales",
  }),
}));
export const relations__posts_v_locales = relations(
  _posts_v_locales,
  ({ one }) => ({
    _parentID: one(_posts_v, {
      fields: [_posts_v_locales._parentID],
      references: [_posts_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: "parent",
  }),
  version_author: one(admins, {
    fields: [_posts_v.version_author],
    references: [admins.id],
    relationName: "version_author",
  }),
  version_featuredImage: one(media, {
    fields: [_posts_v.version_featuredImage],
    references: [media.id],
    relationName: "version_featuredImage",
  }),
  _locales: many(_posts_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [pages.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
}));
export const relations_showcases_locales = relations(
  showcases_locales,
  ({ one }) => ({
    _parentID: one(showcases, {
      fields: [showcases_locales._parentID],
      references: [showcases.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_showcases_rels = relations(
  showcases_rels,
  ({ one }) => ({
    parent: one(showcases, {
      fields: [showcases_rels.parent],
      references: [showcases.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [showcases_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_showcases = relations(showcases, ({ many }) => ({
  _locales: many(showcases_locales, {
    relationName: "_locales",
  }),
  _rels: many(showcases_rels, {
    relationName: "_rels",
  }),
}));
export const relations_categories_locales = relations(
  categories_locales,
  ({ one }) => ({
    _parentID: one(categories, {
      fields: [categories_locales._parentID],
      references: [categories.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_categories = relations(categories, ({ many }) => ({
  _locales: many(categories_locales, {
    relationName: "_locales",
  }),
}));
export const relations_products_options_values_locales = relations(
  products_options_values_locales,
  ({ one }) => ({
    _parentID: one(products_options_values, {
      fields: [products_options_values_locales._parentID],
      references: [products_options_values.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_products_options_values = relations(
  products_options_values,
  ({ one, many }) => ({
    _parentID: one(products_options, {
      fields: [products_options_values._parentID],
      references: [products_options.id],
      relationName: "values",
    }),
    _locales: many(products_options_values_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_products_options_locales = relations(
  products_options_locales,
  ({ one }) => ({
    _parentID: one(products_options, {
      fields: [products_options_locales._parentID],
      references: [products_options.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_products_options = relations(
  products_options,
  ({ one, many }) => ({
    _parentID: one(products, {
      fields: [products_options._parentID],
      references: [products.id],
      relationName: "options",
    }),
    _locales: many(products_options_locales, {
      relationName: "_locales",
    }),
    values: many(products_options_values, {
      relationName: "values",
    }),
  }),
);
export const relations_products_variants_selected_options = relations(
  products_variants_selected_options,
  ({ one }) => ({
    _parentID: one(products_variants, {
      fields: [products_variants_selected_options._parentID],
      references: [products_variants.id],
      relationName: "selectedOptions",
    }),
  }),
);
export const relations_products_variants_locales = relations(
  products_variants_locales,
  ({ one }) => ({
    _parentID: one(products_variants, {
      fields: [products_variants_locales._parentID],
      references: [products_variants.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_products_variants = relations(
  products_variants,
  ({ one, many }) => ({
    _parentID: one(products, {
      fields: [products_variants._parentID],
      references: [products.id],
      relationName: "variants",
    }),
    _locales: many(products_variants_locales, {
      relationName: "_locales",
    }),
    selectedOptions: many(products_variants_selected_options, {
      relationName: "selectedOptions",
    }),
    image: one(media, {
      fields: [products_variants.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_products_locales = relations(
  products_locales,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_locales._parentID],
      references: [products.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: "categories",
  }),
}));
export const relations_products = relations(products, ({ many }) => ({
  options: many(products_options, {
    relationName: "options",
  }),
  variants: many(products_variants, {
    relationName: "variants",
  }),
  _locales: many(products_locales, {
    relationName: "_locales",
  }),
  _rels: many(products_rels, {
    relationName: "_rels",
  }),
}));
export const relations__products_v_version_options_values_locales = relations(
  _products_v_version_options_values_locales,
  ({ one }) => ({
    _parentID: one(_products_v_version_options_values, {
      fields: [_products_v_version_options_values_locales._parentID],
      references: [_products_v_version_options_values.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v_version_options_values = relations(
  _products_v_version_options_values,
  ({ one, many }) => ({
    _parentID: one(_products_v_version_options, {
      fields: [_products_v_version_options_values._parentID],
      references: [_products_v_version_options.id],
      relationName: "values",
    }),
    _locales: many(_products_v_version_options_values_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v_version_options_locales = relations(
  _products_v_version_options_locales,
  ({ one }) => ({
    _parentID: one(_products_v_version_options, {
      fields: [_products_v_version_options_locales._parentID],
      references: [_products_v_version_options.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v_version_options = relations(
  _products_v_version_options,
  ({ one, many }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_options._parentID],
      references: [_products_v.id],
      relationName: "version_options",
    }),
    _locales: many(_products_v_version_options_locales, {
      relationName: "_locales",
    }),
    values: many(_products_v_version_options_values, {
      relationName: "values",
    }),
  }),
);
export const relations__products_v_version_variants_selected_options =
  relations(_products_v_version_variants_selected_options, ({ one }) => ({
    _parentID: one(_products_v_version_variants, {
      fields: [_products_v_version_variants_selected_options._parentID],
      references: [_products_v_version_variants.id],
      relationName: "selectedOptions",
    }),
  }));
export const relations__products_v_version_variants_locales = relations(
  _products_v_version_variants_locales,
  ({ one }) => ({
    _parentID: one(_products_v_version_variants, {
      fields: [_products_v_version_variants_locales._parentID],
      references: [_products_v_version_variants.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v_version_variants = relations(
  _products_v_version_variants,
  ({ one, many }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_variants._parentID],
      references: [_products_v.id],
      relationName: "version_variants",
    }),
    _locales: many(_products_v_version_variants_locales, {
      relationName: "_locales",
    }),
    selectedOptions: many(_products_v_version_variants_selected_options, {
      relationName: "selectedOptions",
    }),
    image: one(media, {
      fields: [_products_v_version_variants.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations__products_v_locales = relations(
  _products_v_locales,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_locales._parentID],
      references: [_products_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v_rels = relations(
  _products_v_rels,
  ({ one }) => ({
    parent: one(_products_v, {
      fields: [_products_v_rels.parent],
      references: [_products_v.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [_products_v_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    categoriesID: one(categories, {
      fields: [_products_v_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
  }),
);
export const relations__products_v = relations(
  _products_v,
  ({ one, many }) => ({
    parent: one(products, {
      fields: [_products_v.parent],
      references: [products.id],
      relationName: "parent",
    }),
    version_options: many(_products_v_version_options, {
      relationName: "version_options",
    }),
    version_variants: many(_products_v_version_variants, {
      relationName: "version_variants",
    }),
    _locales: many(_products_v_locales, {
      relationName: "_locales",
    }),
    _rels: many(_products_v_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_carts = relations(carts, ({ one }) => ({
  user: one(users, {
    fields: [carts.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_cart_items = relations(cart_items, ({ one }) => ({
  cart: one(carts, {
    fields: [cart_items.cart],
    references: [carts.id],
    relationName: "cart",
  }),
  product: one(products, {
    fields: [cart_items.product],
    references: [products.id],
    relationName: "product",
  }),
}));
export const relations_orders = relations(orders, ({ one }) => ({
  user: one(users, {
    fields: [orders.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_order_items_locales = relations(
  order_items_locales,
  ({ one }) => ({
    _parentID: one(order_items, {
      fields: [order_items_locales._parentID],
      references: [order_items.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_order_items = relations(
  order_items,
  ({ one, many }) => ({
    order: one(orders, {
      fields: [order_items.order],
      references: [orders.id],
      relationName: "order",
    }),
    product: one(products, {
      fields: [order_items.product],
      references: [products.id],
      relationName: "product",
    }),
    _locales: many(order_items_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_wishlists = relations(wishlists, ({ one }) => ({
  user: one(users, {
    fields: [wishlists.user],
    references: [users.id],
    relationName: "user",
  }),
  product: one(products, {
    fields: [wishlists.product],
    references: [products.id],
    relationName: "product",
  }),
}));
export const relations_contact_inquiries = relations(
  contact_inquiries,
  () => ({}),
);
export const relations_media_locales = relations(media_locales, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_locales._parentID],
    references: [media.id],
    relationName: "_locales",
  }),
}));
export const relations_media = relations(media, ({ many }) => ({
  _locales: many(media_locales, {
    relationName: "_locales",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    rolesID: one(roles, {
      fields: [payload_locked_documents_rels.rolesID],
      references: [roles.id],
      relationName: "roles",
    }),
    adminsID: one(admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: "posts",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    showcasesID: one(showcases, {
      fields: [payload_locked_documents_rels.showcasesID],
      references: [showcases.id],
      relationName: "showcases",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    cartsID: one(carts, {
      fields: [payload_locked_documents_rels.cartsID],
      references: [carts.id],
      relationName: "carts",
    }),
    "cart-itemsID": one(cart_items, {
      fields: [payload_locked_documents_rels["cart-itemsID"]],
      references: [cart_items.id],
      relationName: "cart-items",
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: "orders",
    }),
    "order-itemsID": one(order_items, {
      fields: [payload_locked_documents_rels["order-itemsID"]],
      references: [order_items.id],
      relationName: "order-items",
    }),
    wishlistsID: one(wishlists, {
      fields: [payload_locked_documents_rels.wishlistsID],
      references: [wishlists.id],
      relationName: "wishlists",
    }),
    "contact-inquiriesID": one(contact_inquiries, {
      fields: [payload_locked_documents_rels["contact-inquiriesID"]],
      references: [contact_inquiries.id],
      relationName: "contact-inquiries",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_preferences_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_company_info_social_media = relations(
  company_info_social_media,
  ({ one }) => ({
    _parentID: one(company_info, {
      fields: [company_info_social_media._parentID],
      references: [company_info.id],
      relationName: "socialMedia",
    }),
  }),
);
export const relations_company_info_locales = relations(
  company_info_locales,
  ({ one }) => ({
    _parentID: one(company_info, {
      fields: [company_info_locales._parentID],
      references: [company_info.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_company_info = relations(
  company_info,
  ({ one, many }) => ({
    logo: one(media, {
      fields: [company_info.logo],
      references: [media.id],
      relationName: "logo",
    }),
    socialMedia: many(company_info_social_media, {
      relationName: "socialMedia",
    }),
    _locales: many(company_info_locales, {
      relationName: "_locales",
    }),
  }),
);

type DatabaseSchema = {
  roles_permissions: typeof roles_permissions;
  roles: typeof roles;
  roles_locales: typeof roles_locales;
  admins_sessions: typeof admins_sessions;
  admins: typeof admins;
  users: typeof users;
  posts: typeof posts;
  posts_locales: typeof posts_locales;
  _posts_v: typeof _posts_v;
  _posts_v_locales: typeof _posts_v_locales;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  showcases: typeof showcases;
  showcases_locales: typeof showcases_locales;
  showcases_rels: typeof showcases_rels;
  categories: typeof categories;
  categories_locales: typeof categories_locales;
  products_options_values: typeof products_options_values;
  products_options_values_locales: typeof products_options_values_locales;
  products_options: typeof products_options;
  products_options_locales: typeof products_options_locales;
  products_variants_selected_options: typeof products_variants_selected_options;
  products_variants: typeof products_variants;
  products_variants_locales: typeof products_variants_locales;
  products: typeof products;
  products_locales: typeof products_locales;
  products_rels: typeof products_rels;
  _products_v_version_options_values: typeof _products_v_version_options_values;
  _products_v_version_options_values_locales: typeof _products_v_version_options_values_locales;
  _products_v_version_options: typeof _products_v_version_options;
  _products_v_version_options_locales: typeof _products_v_version_options_locales;
  _products_v_version_variants_selected_options: typeof _products_v_version_variants_selected_options;
  _products_v_version_variants: typeof _products_v_version_variants;
  _products_v_version_variants_locales: typeof _products_v_version_variants_locales;
  _products_v: typeof _products_v;
  _products_v_locales: typeof _products_v_locales;
  _products_v_rels: typeof _products_v_rels;
  carts: typeof carts;
  cart_items: typeof cart_items;
  orders: typeof orders;
  order_items: typeof order_items;
  order_items_locales: typeof order_items_locales;
  wishlists: typeof wishlists;
  contact_inquiries: typeof contact_inquiries;
  media: typeof media;
  media_locales: typeof media_locales;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  company_info_social_media: typeof company_info_social_media;
  company_info: typeof company_info;
  company_info_locales: typeof company_info_locales;
  relations_roles_permissions: typeof relations_roles_permissions;
  relations_roles_locales: typeof relations_roles_locales;
  relations_roles: typeof relations_roles;
  relations_admins_sessions: typeof relations_admins_sessions;
  relations_admins: typeof relations_admins;
  relations_users: typeof relations_users;
  relations_posts_locales: typeof relations_posts_locales;
  relations_posts: typeof relations_posts;
  relations__posts_v_locales: typeof relations__posts_v_locales;
  relations__posts_v: typeof relations__posts_v;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages: typeof relations_pages;
  relations_showcases_locales: typeof relations_showcases_locales;
  relations_showcases_rels: typeof relations_showcases_rels;
  relations_showcases: typeof relations_showcases;
  relations_categories_locales: typeof relations_categories_locales;
  relations_categories: typeof relations_categories;
  relations_products_options_values_locales: typeof relations_products_options_values_locales;
  relations_products_options_values: typeof relations_products_options_values;
  relations_products_options_locales: typeof relations_products_options_locales;
  relations_products_options: typeof relations_products_options;
  relations_products_variants_selected_options: typeof relations_products_variants_selected_options;
  relations_products_variants_locales: typeof relations_products_variants_locales;
  relations_products_variants: typeof relations_products_variants;
  relations_products_locales: typeof relations_products_locales;
  relations_products_rels: typeof relations_products_rels;
  relations_products: typeof relations_products;
  relations__products_v_version_options_values_locales: typeof relations__products_v_version_options_values_locales;
  relations__products_v_version_options_values: typeof relations__products_v_version_options_values;
  relations__products_v_version_options_locales: typeof relations__products_v_version_options_locales;
  relations__products_v_version_options: typeof relations__products_v_version_options;
  relations__products_v_version_variants_selected_options: typeof relations__products_v_version_variants_selected_options;
  relations__products_v_version_variants_locales: typeof relations__products_v_version_variants_locales;
  relations__products_v_version_variants: typeof relations__products_v_version_variants;
  relations__products_v_locales: typeof relations__products_v_locales;
  relations__products_v_rels: typeof relations__products_v_rels;
  relations__products_v: typeof relations__products_v;
  relations_carts: typeof relations_carts;
  relations_cart_items: typeof relations_cart_items;
  relations_orders: typeof relations_orders;
  relations_order_items_locales: typeof relations_order_items_locales;
  relations_order_items: typeof relations_order_items;
  relations_wishlists: typeof relations_wishlists;
  relations_contact_inquiries: typeof relations_contact_inquiries;
  relations_media_locales: typeof relations_media_locales;
  relations_media: typeof relations_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_company_info_social_media: typeof relations_company_info_social_media;
  relations_company_info_locales: typeof relations_company_info_locales;
  relations_company_info: typeof relations_company_info;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
